name: Android CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: PR Checker
    runs-on: ubuntu-latest
    
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      
      - name: Ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          android: true
          fail_on_error: true
