name: release apk
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'RELEASE') }}
    steps:
      - uses: actions/checkout@v2

      - name: Create Local Properties
        run: touch local.properties
      
      - name: Access Local Properties
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          STORE_FILE: ${{ secrets.STORE_FILE }}
        run:
          echo STORE_PASSWORD= $STORE_PASSWORD >> local.properties
          echo KEY_PASSWORD= $KEY_PASSWORD >> local.properties
          echo KEY_ALIAS= $KEY_ALIAS >> local.properties
          echo STORE_FILE= $STORE_FILE >> local.properties

      - name: Create release sign key
        run: |
          mkdir -p app/keystore
          touch app/keystore/test.jks

      - name: decode release keystore
        run: echo "${{ secrets.KEYSTORE_FILE_BASE_64 }}" | base64 -d > app/keystore/test.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease

      - uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL }}
          initial_comment: '띵덩~ APK~'
          file_type: 'apk'
          file_name: 'test.apk'
          file_path: './app/build/outputs/apk/debug/app-debug.apk'

